### ISSUE TITLE
Removes special character from input string

### ISSUE THREAD

**Issue by BMLande** [blakeembrey/change-case#102]
Hi,
I am trying to convert with Init cap, it works a perfectly great job, But whenever input contains Special Characters (@#$*&&*), it will remove that chars from Sting.

Input => address first line @#$
output=> Address First Line.

Thanks

**Comment by blakeembrey** [comment]
This is working as intended.

**Comment by BMLande** [comment]
Some times  use case is different, In my case needs to make address fields init cap
for ex : mg street , pune 123#
expected output => Mg Street , Pune 123#

**Comment by blakeembrey** [comment]
This package won't be able to do that for you, you'll be better off writing the logic for yourself. E.g.

```
value.replace(/\s\S/g, x => x.toUpperCase())
```
