### ISSUE TITLE
capitalCase method replace 'ñ' and accented letters by white space.

### ISSUE THREAD

**Issue by RicardoASalas** [blakeembrey/change-case#138]
It doesnt't work for spanish words when replaces 'ñ' and accented letters by white space, capitalizing the following word.

Method: capitalCase().
Exp: María Muñoz ---> Mar A Mu Oz

**Comment by blakeembrey** [comment]
This is currently by design, will likely be changed in the next major release. There’s no internationalization support for the current release.
