### ISSUE TITLE
lowerCase and upperCase are not compatible with chrome devtools environment.

### ISSUE THREAD

**Issue by janryWang** [blakeembrey/change-case#139]
![image](https://user-images.githubusercontent.com/4060976/100471384-246b0600-3115-11eb-948a-4f4f248ebf6c.png)

Because the object key uses special characters, there may be strict requirements in the sandbox environment.

**Comment by blakeembrey** [comment]
How can someone replicate this? I’ve used it in the chrome dev tools without issue before.

**Comment by janryWang** [comment]
> How can someone replicate this? I’ve used it in the chrome dev tools without issue before.

It’s not run on default devtools. I developed a chrome extension. It will throw error in the extension

**Comment by blakeembrey** [comment]
Can you share how someone can replicate this?

**Comment by janryWang** [comment]
> Can you share how someone can replicate this?

This scene is difficult to reproduce, but if I change the code to the following, it will work.

```
{
      "i̇": "\u0049",
      "j̇": "\u004A",
      "į̇": "\u012E",
      "i̇̀": "\u00CC",
      "i̇́": "\u00CD",
      "i̇̃": "\u0128"
 }
```

Just wrap special characters in quotation marks...

**Comment by blakeembrey** [comment]
The quotes are automatically stripped by [prettier](https://prettier.io) and I don't have any interest in maintaining libraries without prettier right now. I'm going to close this as won't fix.
