### ISSUE TITLE
Diacritics are removed

### ISSUE THREAD

**Issue by kissu** [blakeembrey/change-case#152]
Hello ! 👋🏻 

I do have the following string: `Nom donné à l'adresse`
`paramCase` gaves me `nom-donn-l-adresse` rather than `nom-donne-a-l-adresse`, which looks more like the behavior it should have in this case.

**Comment by kissu** [comment]
Saw this one: https://github.com/blakeembrey/change-case/issues/138#issuecomment-733239699
I guess it's on the roadmap but not implemented yet ?

**Comment by spacecakes** [comment]
Same goes for Swedish letters like ÅÄÖ

**Comment by blakeembrey** [comment]
This has been fixed with `change-case@5.0.0`. Please update and let me know if you still see any issues.
