### ISSUE TITLE
Add the option to chain methods

### ISSUE THREAD

**Issue by mcorbanini** [blakeembrey/change-case#16]
A good enhancement IMO would be to be able to do something like:

```javascript
changeCase('someWord').chain()
  .toSnakeCase()
  .firstUpperCase()
  ...
  .value()
```

If it's a good idea I can create a pull request to add that.

**Comment by blakeembrey** [comment]
@mcorbanini I'm not sure it'd be a good idea. I would like to keep the library small, but I think it'd be possible to make a utility for this. E.g. `chain('someWorld').map(changeCase.toSnakeCase).map(changeCase.firstUpperCase)`.

**Comment by mcorbanini** [comment]
Yea you're right. Thanks for the quick response!
