### ISSUE TITLE
Shouldn't sentence case lead with an uppercase letter?

### ISSUE THREAD

**Issue by itsravenous** [blakeembrey/change-case#20]
I.e:

```javascript

changeCase.sentence('whaleShark') // -> 'Whale shark'
```

This isn't particularly significant for what I'm doing (generating a friendly name for a model type to use in an error message), but I was curious to know whether my suspicion is correct or not :)

**Comment by blakeembrey** [comment]
@itsravenous Unfortunately it's a naming issue. I'd have to release a new major version to fix it and I haven't gotten around to it. See https://github.com/blakeembrey/sentence-case/issues/4

**Comment by itsravenous** [comment]
Fair enough! I'll keep an eye on this. I can always submit a PR if you'd rather, though I'm hugely busy at work at the moment so it could be a while ;)

**Comment by blakeembrey** [comment]
Replaced, finally, with `3.0.0` 😄
