### ISSUE TITLE
data with numbers in it

### ISSUE THREAD

**Issue by jmls** [blakeembrey/change-case#21]
I have a string "amazon s3 data" that I have pushed through paramCase. The result is "amazon-s-3-data" , where I really wanted "amazon-s3-data"

is there any way of doing this, or will I have to do some manipulation myself ?

**Comment by blakeembrey** [comment]
@jmls Unfortunately that's a feature. It is possible we can make it easier to manipulate, but yes, you'll need to do some manipulation yourself. The issue really is that there's no "detection" of the the format, only naive sanitization. 

Potentially, `sentence-case` (the root module) could accept a function for `replace` and then you could manipulate it yourself. But I'd really need more information to know whether it's a worthwhile improvement for your use-case.

Reference: https://github.com/blakeembrey/sentence-case/blob/master/sentence-case.js#L33-L34
