### ISSUE TITLE
AP Style?

### ISSUE THREAD

**Issue by huphtur** [blakeembrey/change-case#22]
Perhaps a silly request, but is it possible to add AP style capitalization?

More info: http://titlecapitalization.com/

**Comment by blakeembrey** [comment]
Not silly at all, it's a valid request. I'll look into it when I can :smile:

**Comment by unional** [comment]
A silly question, what's AP style? :beer

**Comment by cbrnr** [comment]
AP style caps (in addition to Chicago and APA) would be super-useful, you can see the rules in the linked site above. Here's another site which explains the three most common styles: http://capitalizemytitle.com/

**Comment by blakeembrey** [comment]
Absolutely down to accept a PR to `title-case` for this change 👍

**Comment by blakeembrey** [comment]
I'm going to close this for now. I'd love to make a note in the README of this module and `title-case` of a proper AP-case module, if a preferred one exists. Currently I'm going to keep `change-case` and related modules on just switching between case modes internally.
