### ISSUE TITLE
Support changing case of object values

### ISSUE THREAD

**Issue by anthonator** [blakeembrey/change-case#23]
Add the ability to pass an object to a `change-case` function to recurse the object and apply the change to object values.

**Comment by blakeembrey** [comment]
It might be a little out of scope, but it's easy enough to do. I also found https://github.com/claudetech/js-change-object-case. May I ask why you closed the issue?

```js
var changeCase = require('change-case')

function (in, method) {
  var out = {}

  Object.keys(in).forEach(function (key) {
    out[changeCase[method](key)] = in[key]
  })

  return out
}
```

**Comment by anthonator** [comment]
I closed the issue because I was tired when I posted this and it didn't make any sense. I actually needed the opposite of what I stated. I needed the keys to be cased and not the value. I just implemented what I needed and didn't bother opening another issue.

I'd love to see this in `change-case` proper though.
