### ISSUE TITLE
support for "kebab case"

### ISSUE THREAD

**Issue by oriSomething** [blakeembrey/change-case#24]
not sure this is the right term. i'm talking about [this (kebab case)](https://lodash.com/docs#kebabCase).
it's very useful for some of the web programmers

**Comment by blakeembrey** [comment]
I only encountered that term recently myself. Since this library predates me learning that, it happens to be called [param-case](https://github.com/blakeembrey/change-case#paramcase).

**Comment by vjpr** [comment]
I came looking for kebab case too. Could we have a `kebab-case` alias?

Lodash uses the term kebab case.

I've never heard of `param-case` and I don't think it makes much sense. Parameters (`function(foo-bar) {}`) is JS cannot be `param-case`.

http://stackoverflow.com/questions/11273282/whats-the-name-for-hyphen-separated-case/12273101

**Comment by ValeriiVasin** [comment]
Also never heard about param-case :) everyone here called it kebab-case... As far as i got there are no plans to add alias?

P.S. Even [wiki article](https://en.wikipedia.org/wiki/Letter_case#Special_case_styles) has info about kebab-case, not a param-case :) if it is an argument :)

**Comment by blakeembrey** [comment]
You're welcome to submit a PR. The `kebab-case` name on NPM is already taken, however, so renaming it properly won't happen.
