### ISSUE TITLE
`title-case` capitalizes "from" (to "From")

### ISSUE THREAD

**Issue by iacobfred** [blakeembrey/change-case#265]
The `titleCase` function seems to mistakenly capitalize the preposition "from".

Example:
    before `titleCase`: "evolution of the earliest amphibians from freshwater fish"
    after `titleCase: "Evolution of the Earliest Amphibians From Freshwater Fish"

Expected behavior:
    after `titleCase: "Evolution of the Earliest Amphibians from Freshwater Fish"

**Comment by blakeembrey** [comment]
Seems subjective, do you have a reference for your expected behavior?

**Comment by iacobfred** [comment]
You're right. I thought prepositions of 5+ letters are supposed to be capitalized, but now I see that AP and a couple other guides say to capitalize prepositions of 4+ letters.

**Comment by blakeembrey** [comment]
Yeah, it's all a little subjective. I was looking at this [example](https://apastyle.apa.org/style-grammar-guidelines/capitalization/title-case) to double check which uses "From" as the example. I don't use this module personally and just opt for writing in sentence case 🤷
