### ISSUE TITLE
title-case: a quoted word with a period in it doesn't get capitalized

### ISSUE THREAD

**Issue by teddybradford** [blakeembrey/change-case#266]
I think I found a bug in `title-case`: When a string has a quoted word with a period in it, that word isn't capitalized.

For example:
```js
titleCase("Is human activity responsible for the climate emergency? New report calls it ‘unequivocal.’")
// Is Human Activity Responsible for the Climate Emergency? New Report Calls It ‘unequivocal.’
```

I would expect `unequivocal` to be capitalized, but it is not.

**Comment by blakeembrey** [comment]
I have released a fix for this here: https://github.com/blakeembrey/change-case/releases/tag/title-case%404.1.0.
