### ISSUE TITLE
Consider a new release

### ISSUE THREAD

**Issue by samvloeberghs** [blakeembrey/change-case#277]
Hi, can a new release + publish on npm be considered?
I see a lot of updated dependencies and commits that have not been included in the last release ( since end of 2020 )

Thanks!

**Comment by blakeembrey** [comment]
The commits are development dependencies and there were no meaningful changes needing publishing since 2020. There were two non-dev dependency changes that were related to reducing package size, but I've been working on refactoring code this week and it would supersede those changes now.
