### ISSUE TITLE
Title Case not working with a camelCase string

### ISSUE THREAD

**Issue by btxtiger** [blakeembrey/change-case#279]
Seems Title Case not working with a camelCase string. 
I needed to use `titleCase(sentenceCase('userSessions'))` to get `User Sessions`. 
Otherwise the output remains camelCase.

**Comment by rinogo** [comment]
This confused me, too. It's possible that [this Issue](https://github.com/blakeembrey/change-case/issues/124) is related.

Regardless, I wonder if you could add spaces before all capitalized letters first...

Maybe try something like this?
```
titleCase(sentenceCase('userSessions'.replace(/([A-Z])/, ' $1')))
```

**Comment by blakeembrey** [comment]
I'm not sure I follow this issue, but it works for me: https://runkit.com/blakeembrey/62105d3771ff5600088d0b2d.

In that example of `capitalCase` and `titleCase` are working.

**Comment by blakeembrey** [comment]
Oh, I think the complaint is that `titleCase` doesn't automatically turn camel case into something else. That's expected behavior, you want `capitalCase` (title case is for just turning text into a "title" according to basic English rules). That's why it's not included in `change-case` at all.
