### ISSUE TITLE
Why are tslib and typescript dependencies of these libraries?

### ISSUE THREAD

**Issue by henry-filosa** [blakeembrey/change-case#281]
Since these packages are retrieved by npm as compiled JS, it seems unnecessary that some of these packages have them marked as dependencies.

**Comment by dmnsgn** [comment]
Seems to be impacting the size of the lib quite a lot: https://bundlephobia.com/package/change-case@4.1.2
<img width="1033" alt="Screenshot 2023-01-17 at 11 02 29" src="https://user-images.githubusercontent.com/1636460/212882709-8e5bc1cb-8259-430f-b433-cee7edd4e171.png">

**Comment by blakeembrey** [comment]
This has been fixed with `change-case@5.0.0`. Please update and let me know if you still see any issues.
