### ISSUE TITLE
Convert string to lowercase prior to processing

### ISSUE THREAD

**Issue by PythonCoderAS** [blakeembrey/change-case#288]
There were no statements written that stated that only lowercase inputs were accepted, and I had to find out the hard way. I think it would be nice if the library could automatically do the lowercase conversion or at least note it in the documentation so that developers know to pre-lowercase their strings.

**Comment by blakeembrey** [comment]
It does convert before processing. Maybe you can provide an example of your problem so it can be reviewed?

**Comment by PythonCoderAS** [comment]
Here is an example:

```js
> console.log(titleCase("PRIMARY"))
PRIMARY
> console.log(titleCase("PRIMARY".toLowerCase()))
Primary
```

**Comment by blakeembrey** [comment]
I see. Title case is different to the rest of the functionality because it isn’t part of the case changing. It’s not a requirement for it to be lower-case, but it’s not changing that because it’s possible you’re using a valid acronym (e.g. UUID).
