### ISSUE TITLE
Could noCase package support Chinese word

### ISSUE THREAD

**Issue by ihepta** [blakeembrey/change-case#289]
hi, Blake Embrey
first of all, thank you for your excellent toolkit.
but i find there are two lines code in noCase package
```
// Remove all non-word characters.
const DEFAULT_STRIP_REGEXP = /[^A-Z0-9]+/gi;
```
In my scenario, it would remove all chinese word, like '中文'.

Is it be possible to support chinese word? 
just like pass the chinese word to this package, return the chinese word itself rather than the empty word or anything else.

**Comment by blakeembrey** [comment]
This has been fixed with `change-case@5.0.0`. Please update and let me know if you still see any issues.
