### ISSUE TITLE
Characater problem

### ISSUE THREAD

**Issue by onurkanbakirci** [blakeembrey/change-case#291]
When i try to use `change-case` as a extension in vscode, i faced some problems. Procedure i am following is;

1) Highlight `İZMİR` as a string in vscode
2) open command palette via `command` + `shift` + `p` keyboard combination  
3) Select `Change Pascal Case` future and then press enter

After these steps i expect that the result of process should be;

`İzmir`

But actual result is 

`İzmi̇r`

There is an incorrect translation between upper "İ" to lower "i" character.

**Comment by blakeembrey** [comment]
When I use [DuckDuckGo](https://duckduckgo.com/?q=lower+case++%C4%B0&t=iphone&ia=answer) it lower cases to the second result. Are you expecting a certain locale behavior? I know I have overrides for that behavior here: https://github.com/blakeembrey/change-case/blob/master/packages/lower-case/src/index.ts

**Comment by blakeembrey** [comment]
This should be fixed with `change-case@5.0.0`. Please update and let me know if you still see any issues.
