### ISSUE TITLE
brackets are removed from tite

### ISSUE THREAD

**Issue by Morriz** [blakeembrey/change-case#292]
Hi, I was wondering why this lib removes chars from the string like `(|)|[|]`. I think this lib is being overly opinionated and it should be configurable. By default it should only concern itself about casing imo.

**Comment by blakeembrey** [comment]
I'm going to close this as won't fix but I'm open to fixing it if I can understand the expected use case and behavior. Why are you passing things that can't be cased? What would you want the result to be of `camelCase("foo(bar)")`? Arguably it is `fooBar`...
