### ISSUE TITLE
Apostrophe not supported

### ISSUE THREAD

**Issue by Eyal17** [blakeembrey/change-case#293]
Hi,
Whenever i want to use apostrophe, i'm getting white space instead.
For example:

Assistant's name => Assistant S Name

It will be possible to support the using of apostrophe?

Thanks.

**Comment by blakeembrey** [comment]
The base `change-case` libraries are only intended for switching between the supported cases. What use case do you have for this on `Assistant's name`? Perhaps you are using the [`title-case`](https://github.com/blakeembrey/change-case/tree/master/packages/title-case) module? It's supported there.
