### ISSUE TITLE
Access to system specific variables beyond file name like package name, date etc

### ISSUE THREAD

**Issue by tipmaster** [blakeembrey/change-case#299]
This may be possible already and if so apologies for missing it in the documentation. For the files I create I would want to interpolate variables like package name, date etc like I can with standard VSCode snippets. I understand I can do custom variables. Using the standard snippet syntax for these such as  ${CURRENT_DATE} did not yield any success. Is this theoretically supported and if so how?

**Comment by blakeembrey** [comment]
This doesn't appear to be related to this repo.
