### ISSUE TITLE
 "Capitalize" is not working properly.

### ISSUE THREAD

**Issue by Tiagofsant** [blakeembrey/change-case#300]
Problem description.

***

In the string: "GERENTE DE TECNOLOGIA DA INFORMAÇÃO," when using the capitalCase method, it returns as follows: "Gerente De Tecnologia Da Informa O," which means it's removing the "Ç" and the "ã". 

How can I solve this, knowing that this string is dynamically returned from the API?

**Comment by blakeembrey** [comment]
This has been fixed with `change-case@5.0.0`. Please update and let me know if you still see any issues.
