### ISSUE TITLE
TypeScript support broken in 5.0

### ISSUE THREAD

**Issue by Hypnosphi** [blakeembrey/change-case#304]
Reproduction: https://github.com/Hypnosphi/change-case-ts-issue

```
 % npm run build

> change-case-ts-issue@1.0.0 build
> tsc

index.ts:1:25 - error TS2307: Cannot find module 'change-case' or its corresponding type declarations.

1 import {camelCase} from 'change-case'
```

**Comment by blakeembrey** [comment]
See https://github.com/blakeembrey/change-case/pull/303. Rather it’s node ESM support that is broken. This package works correctly in typescript if you have it configured for node 16 resolution, which is the first resolution version of TypeScript supporting ESM.

**Comment by moltar** [comment]
I think the type of support is broken overall. This is the best tool for diagnostics. The [author](https://github.com/andrewbranch) of the tool was one of the core developers of the TypeScript compiler itself, so he knows this inside and out.

https://arethetypeswrong.github.io/?p=change-case%405.0.1

You can learn more here: https://github.com/arethetypeswrong/arethetypeswrong.github.io

**Comment by blakeembrey** [comment]
@moltar No, the link literally says it's correct: 
![CleanShot 2023-10-03 at 10 30 14@2x](https://github.com/blakeembrey/change-case/assets/1088987/e4de72b8-7991-47ea-aede-65137877185f)

I am not supporting CommonJS and Node10 resolution.

**Comment by blakeembrey** [comment]
I appreciate the link though, I will include this in the README so it's clear I intentionally will not support `node10` or CommonJS.
