### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by ptahchiev** [blakeembrey/change-case#309]
`changeKeys.pascalCase('basictempalte')` returns `basictemplate`

**Comment by blakeembrey** [comment]
This is the expected behavior. It isn't a dictionary. It can't convert `foobar` to `fooBar` magically, it only converts between existing cases such as `foo bar` to `FooBar`.

**Comment by ptahchiev** [comment]
I don't want it to convert from `foobar` to `fooBar`. I want it to convert from `foobar` to `Foobar`. This library does it:
https://www.npmjs.com/package/pascal-case
but somebody put a message that it is deprecated and we should switch to change-case which doesn't behave this way.

**Comment by blakeembrey** [comment]
Can you create a reproduction? There's a dozen tests that show this working. What's your code? Why's it using `changeKeys`?

**Comment by blakeembrey** [comment]
Here's a very simple test case that is working: https://github.com/blakeembrey/change-case/blob/aed9a6cbf8b1d5d1484d3bb8d179f8756afde606/packages/change-case/src/index.spec.ts#L53-L70

**Comment by ptahchiev** [comment]
Why's it using changeKeys? Because that's what the README file says. From what I understand there's no other documentation so i'm doing what this file says: https://github.com/blakeembrey/change-case/blob/main/packages/change-case/README.md

Do I need to use something else?

**Comment by blakeembrey** [comment]
Can you provide any code of what you're doing?

**Comment by blakeembrey** [comment]
I think I can see the confusion though, I'll try and improve the docs tomorrow. I had recently condensed it and I see you've just copied and pasted the first code you've seen. You want to import like:

```js
import * as changeCase from "change-case";
```

The export you're using was for changing object keys, i.e. `{ basictemplate: true }` to `{ Basictemplate: true }`.

**Comment by blakeembrey** [comment]
I updated and published a change to the [README](https://github.com/blakeembrey/change-case/blob/main/packages/change-case/README.md) with an `import` example for the basic library features, do you think that helps if someone else were to end up in your situation?

**Comment by ptahchiev** [comment]
Yes, using this works fine:
```
import * as changeCase from "change-case";
```
No idea why.
