### ISSUE TITLE
Failing after upgrade to v5

### ISSUE THREAD

**Issue by llong2195** [blakeembrey/change-case#311]
Package has been working fine with v4.1.2

However, after upgrading to v5, I get the following error:

`Error: No "exports" main defined in E:\backend\node_modules\change-case\package.json`

My import command is just `import { camelCase } from 'change-case';` which worked fine before.

minirepo: https://codesandbox.io/p/sandbox/long-leftpad-7hd63p?file=%2Fsrc%2Findex.js%3A1%2C43

**Comment by pwa-tapptic** [comment]
Same here, using `"change-case": "^5.1.2"`

**Comment by blakeembrey** [comment]
This package does not work with CommonJS any more. Please see the README or release notes for more information.
