### ISSUE TITLE
Convert to support es2015

### ISSUE THREAD

**Issue by unional** [blakeembrey/change-case#32]
This applies to all sub-packages (I am using `pascal-case` and `param-case` directly).

Currently, es2016 syntax doesn't work:

```ts
import * as changeCase from 'change-case'
```
![image](https://cloud.githubusercontent.com/assets/3254987/21989249/0831b330-dbbf-11e6-969e-61151c6b1808.png)

**Comment by blakeembrey** [comment]
You would need to use the regular require syntax. I don't think I'll be making this change anytime soon myself, at least not until native ES6 node modules land.

**Comment by unional** [comment]
It prevents using these libraries in es6 modules, such as bundling using `rollup`.

Too bad I don't have much spare time, if not I can do some PRs. 🌷

**Comment by blakeembrey** [comment]
I don't think it's useful to pre-emptively split the ecosystem to try and support tooling I don't use myself. Best to use CommonJS until node.js native support lands and find a migration path from there.

**Comment by unional** [comment]
Oh, not really. Just something like this would be fine:
https://github.com/JsCommunity/make-error/blob/master/index.js#L141-L142

I'm using your `mark-error-cause` that works in both:
```ts
const makeErrorCause = require('make-error-cause')

import * as makeErrorCause from 'make-error-cause'

import { BaseError } from 'make-error-cause'

t.is(makeErrorCause.BaseError, BaseError)
```

**Comment by blakeembrey** [comment]
Ok, so that should work for this module already. So it's just all the dependency that would need to be updated? What's the benefit of updating them to have an extra export property? Note that each of the sub-modules are already as small as they could be and if it works on this module then it should import only the required pieces already right?

**Comment by unional** [comment]
I think so.
I can change one (`pascal-case`) to demo it.

> What's the benefit of updating them to have an extra export property?

Without that extra export, that's the error I got in the OP, `tsc` can't compile when `target: 'es2015'`


btw, when you are talking about two bundles, ideally yes.
That's what I'm doing. e.g.:
https://github.com/unional/color-map

The way `make-error-cause` (and `make-error`) work has a slightly weird behavior:

```ts
// typescript
const mec = require('make-error-cause')
import * as makeErrorCause from 'make-error-cause'

t.is(typeof makeErrorCause, 'function')
t.is(mec, makeErrorCause)
```

Normally `* as makeErrorCause` would be an immutable object.

I have not tried in babel, but with the "bad" synthetic import, this should work:

```js
// babel
import makeErrorCause from 'make-error-cause'
t.is(typeof makeErrorCause, 'function')

new CustomError = new makeErrorCause.BaseError(...)
```

**Comment by rektide** [comment]
I'm using https://github.com/nolanlawson/cjs-to-es6 to consume this from the browser. Good luck everyone.

**Comment by ilyakamens** [comment]
I'm using gulp, so ended up doing this:
```
gulp.src('node_modules/change-case/change-case.js')
      .pipe(bro({standalone: '_changeCase'}))
      .pipe(concat('change-case.min.js'))
      .pipe(gulp.dest('node_modules/change-case')),
```

**Comment by ozanmuyes** [comment]
Here's a workaround for Rollup; use 'rollup-plugin-commonjs' in conjunction with 'rollup-plugin-node-resolve' for an input file like the following;

```javascript
import camel from 'camel-case';

// use camel() where needed
```

and this Rollup config;

```javascript
export default {
  //
  plugins: [
    resolve(),
    commonjs();
    // babel and/or uglify may come here
  ],
};
```

**Comment by blakeembrey** [comment]
Done on `master`.
