### ISSUE TITLE
Postfixing characters

### ISSUE THREAD

**Issue by komyg** [blakeembrey/change-case#322]
Hi, I saw that you've added the option to [prefix characters](https://github.com/blakeembrey/change-case/releases/tag/change-case%405.1.0).

Would you consider adding the option to postfix characters as well? For example: keeping the underscore at the end of `type_`?

We are using `change-case` to generate typescript code, and it would be useful for us to be able to keep some postfixed characters, so that we don't accidentally generate a reserved keyword such as `type` or `const`.

**Comment by blakeembrey** [comment]
SGTM. Done and [released](https://github.com/blakeembrey/change-case/releases/tag/change-case%405.3.0).
