### ISSUE TITLE
bug: lookbehind not supported on Safari < 16.4

### ISSUE THREAD

**Issue by aparajita** [blakeembrey/change-case#328]
Hi, thanks as always for this package.

[This commit](https://github.com/blakeembrey/change-case/commit/b7afd3cab717f0c0a82c77db6777839a1469e8aa) from 2 days ago broke the package for all users of Safari < 16.4 – which is a lot!

Specifically, you are using a positive lookbehind here, which is not supported:

https://github.com/blakeembrey/change-case/blob/17a27ce064572920f11f44b3686a9f9cf422e9c7/packages/change-case/src/index.ts#L6

Hope you can fix it.

**Comment by blakeembrey** [comment]
Thanks for the report, I've fixed it in the [latest release](https://github.com/blakeembrey/change-case/releases/tag/change-case%405.4.1).
