### ISSUE TITLE
Is it possible to add "main" key to package.json?

### ISSUE THREAD

**Issue by alarner** [blakeembrey/change-case#329]
I'm trying to use change-case in a react native project, but the metro bundler is expecting a "main" key in the [package.json](https://github.com/blakeembrey/change-case/blob/main/packages/change-case/package.json#L31). When I add `"main": "./dist/index.js",` it works just fine. I'm happy to submit a PR but was a bit unsure how the project was structured and if I should make the change to just change-case or also sponge-case, swap-case, etc.

**Comment by blakeembrey** [comment]
Based on [the docs](https://nodejs.org/api/packages.html#main-entry-point-export) it seems fine to add it, but I’d definitely ask the metro bundler why it doesn’t support exports.

**Comment by blakeembrey** [comment]
Feel free to add the field to all packages if you do want to make the PR.
