### ISSUE TITLE
NPM says this repo has no README

### ISSUE THREAD

**Issue by abdulhannanali** [blakeembrey/change-case#33]
Well it does, NPM! 

![image](https://cloud.githubusercontent.com/assets/8170969/22139666/45017a32-df09-11e6-9516-7a1200a42492.png)

**Comment by blakeembrey** [comment]
That seems odd. I'm wondering if it's been broken on NPM since 3.0, or whether something recently changed on the NPM-side. Either way, I can try re-releasing to see if it fixes the README situation.

**Comment by blakeembrey** [comment]
Looks good again now: https://www.npmjs.com/package/change-case. Thanks for the report!

**Comment by abdulhannanali** [comment]
@blakeembrey Cool, It does now, thanks a lot.. I saw this problem with some other packages too, don't know why this happened
