### ISSUE TITLE
paramCase is missing from latest v5 release

### ISSUE THREAD

**Issue by lk77** [blakeembrey/change-case#331]
Hello,

when i try to import paramCase from change-case it now fails after the update,
and i don't find it on github either 

this url :

https://github.com/blakeembrey/change-case/tree/main/packages/param-case 

return 404, 

and i don't find a paramCase function here :

https://github.com/blakeembrey/change-case/blob/main/packages/change-case/src/index.ts

thanks !

**Comment by blakeembrey** [comment]
It’s called kebab case now: https://github.com/blakeembrey/change-case/releases/tag/change-case%405.0.0

**Comment by lk77** [comment]
thanks !
