### ISSUE TITLE
Add sArCaStIcCaSe

### ISSUE THREAD

**Issue by GildedPleb** [blakeembrey/change-case#336]
This is a proposal to add sarcastic case. 

## Rules
- words start with lowercase and alternate to uppercase on each letter
- words are seperated by hyphens and underscores which alternate at each word

## Example
`tHiS-iS_sArCaStIc-cAsE`

## Use Cases
1. Data Mocking (instant visual verification of mocked/fake data, in addiiton to 4)
1. Testing
1. Adding yet another case option if more cases are needed
1. Communicate sarcasm/irony/memes/mocking
1. Generally adding levity

**Comment by jlarmstrongiv** [comment]
Very similar to `Case.random('Hello!')   -> 'hElLO!'` in https://www.npmjs.com/package/case

**Comment by blakeembrey** [comment]
This is similar to the existing `sponge-case`: https://github.com/blakeembrey/change-case/tree/main/packages/sponge-case? Or do you specifically want to add this to the case changing library function so you can convert from other cases like camel case into this case? The main problem is that it wouldn't be able to easily convert back, so I think just using `sponge-case` or the `case` library @jlarmstrongiv mentions is probably better.
