### ISSUE TITLE
[bug]: Sentence case isn't changing the case correctly

### ISSUE THREAD

**Issue by JoltCode** [blakeembrey/change-case#339]
![image](https://github.com/blakeembrey/change-case/assets/46378904/dfd3b6a1-6872-4cdc-bdd2-1750dc742541)

As you can see, it's removing all punctuation, and not capitalising correctly either.

Desired output is the same as the input;
> The quick brown fox jumps over the lazy dog. Hello there!

**Comment by blakeembrey** [comment]
That’s by design, anything in the change-case library works this way and is documented in the respective README. Maybe you want to try the title-case library instead?

**Comment by blakeembrey** [comment]
Maybe the README isn’t clear enough? I can try updating it if you have an idea of what you think is poorly documented. I recently shrunk the document to try and improve clarity, so maybe it’s that?

**Comment by JoltCode** [comment]
> Maybe the README isn’t clear enough? I can try updating it if you have an idea of what you think is poorly documented. I recently shrunk the document to try and improve clarity, so maybe it’s that?

Yeah I couldn't see that punctuation was removed anywhere - but I probably missed it!

**Comment by blakeembrey** [comment]
It wasn't very clear, I tried updating it here: https://github.com/blakeembrey/change-case/commit/759c9a5430844fe5b0dcc004373eee8e1e85dc42. Let me know if that helps. Proper sentence casing is also a tricky problem, so do let me know if the `title-case` library helps and if anything is missing. The main difficulty I had working on that library is that it's hard to tell if something is meant to be upper/lower with domain specific words.

**Comment by JoltCode** [comment]
> It wasn't very clear, I tried updating it here: [759c9a5](https://github.com/blakeembrey/change-case/commit/759c9a5430844fe5b0dcc004373eee8e1e85dc42). Let me know if that helps. Proper sentence casing is also a tricky problem, so do let me know if the `title-case` library helps and if anything is missing. The main difficulty I had working on that library is that it's hard to tell if something is meant to be upper/lower with domain specific words.

Ahh that's perfect! Thanks so much!! 😄
