### ISSUE TITLE
`camelCase` function appears incorrect

### ISSUE THREAD

**Issue by jameskhedley** [blakeembrey/change-case#351]
I borrowed the test cases from lodash and got the following:
```
Input: snake_case, 	expected: snakeCase, actual: snakeCase
Input: 12 feet, 	expected: 12Feet, actual: 12Feet
Input: too legit 2 quit, 	expected: tooLegit2Quit, actual: tooLegit_2Quit
Input: walk 500 miles, 	expected: walk500Miles, actual: walk_500Miles
Input: xhr2 request, 	expected: xhr2Request, actual: xhr2Request
Input: enable 6h format, 	expected: enable6HFormat, actual: enable_6hFormat
Input: enable 24H format, 	expected: enable24HFormat, actual: enable_24HFormat
```

Are underscores before a number intentional?

**Comment by blakeembrey** [comment]
The unit tests are here: https://github.com/blakeembrey/change-case/blob/main/packages/change-case/src/index.spec.ts

The docs mention it here:

> By default, pascalCase and snakeCase separate ambiguous characters with _. For example, V1.2 would become V1_2 instead of V12. If you prefer them merged you can set mergeAmbiguousCharacters to true.

It could probably be clearer, but yes, it's intentional.

**Comment by blakeembrey** [comment]
Without the underscore, something like `xhr2Request` from your snippet above can't be undone back into `xhr2 request`. If you don't split on `xhr2` to make it work, the subsequent reversal doesn't work because you'd get `enable6h format`.

**Comment by jameskhedley** [comment]
Thanks for the explanation.
