### ISSUE TITLE
Identify case of string?

### ISSUE THREAD

**Issue by giorgio79** [blakeembrey/change-case#47]
Would be nice to identify case of string, eg:

change-case.identifyCase("Love"); -> titleCase
change-case.identifyCase("LOVE"); -> All Uppercase
etc

**Comment by blakeembrey** [comment]
That would definitely be interesting to see. Not sure the best way to achieve it though. The naive approach is just to build this from scratch. I'll definitely consider it for the next release (but I'm not sure when that'll be)!

**Comment by giorgio79** [comment]
Just found this lib that identifies case too :) https://www.npmjs.com/package/case

**Comment by blakeembrey** [comment]
Awesome! I'll close this issue out as-is. I'm always happy if someone wants to add something like this, but it's not something I'm planning to add myself.
