### ISSUE TITLE
Consider adding "title_snake_case" or similar.

### ISSUE THREAD

**Issue by gwk** [blakeembrey/change-case#52]
I just ran into a situation where I had a bunch of (lowercase) snake_case symbols and needed each word to be in title case. Sadly change-case does not handle this flavor. For example, I want to be able to transform `some_thing` into `Some_Thing`. I know this is a little uncommon but it would have been very helpful just now!

I am using change-case via the VSCode extension and it is tremendously useful. Thanks for the great library!

**Comment by blakeembrey** [comment]
Maybe we can re-use `Header-Case` and swap out the delimiter? However, that doesn't help much in the VS code extension. Is there a name for this format that's better than capital snake case?

**Comment by blakeembrey** [comment]
This has been added in `change-case@5.0.0`. It's called `pascalSnakeCase`.
