### ISSUE TITLE
No support for apostrophe (genitive 's)

### ISSUE THREAD

**Issue by kheyse-oqton** [blakeembrey/change-case#54]
E.g. "Ronny's brother" is transformed to "Ronny S Brother"

**Comment by blakeembrey** [comment]
This is intentional as-is. It's not clear how that is meant to change to cases such as `param-case`.

**Comment by nmccready** [comment]
Same problem in `titleCase` .

`titleCase('TESTING with dash-es and a'postrophes')`

```
    - Expected
    + Received

    - Testing With Dash-Es And A'Postrophes
    + Testing With Dash Es And A Postrophes
```

**Comment by nmccready** [comment]
I see why this is happening due to `noCase`, is it possible to make `noCase` optional? `NON_WORD_REGEXP` is the problem .

**Comment by nmccready** [comment]
#19 is the same issue / related

**Comment by blakeembrey** [comment]
I’d recommend using another library for this behavior for now. I’ll do a refactor at some point to clarify the name of this package.

**Comment by nmccready** [comment]
When you refactor are you considering using `lerna` as it would help immensely with the micro repos.

```
export const titleWithPunc = (words, { doLowerRest = true, splitter = /[^\d\s]+/g } = {}) =>
  words.replace(splitter, (word) => {
    let rest = word.substr(1);

    if (doLowerRest) {
      rest = rest.toLowerCase();
    }

    return word.charAt(0).toUpperCase() + rest;
  });
```


```
import { titleWithPunc } from './changeCase';

describe('ourChangeCase', () => {
  describe(titleWithPunc.name, () => {
    it('single word', () => expect(titleWithPunc('crap')).toEqual('Crap'));

    it('two words', () => expect(titleWithPunc('crap beer')).toEqual('Crap Beer'));

    describe('keeps punctuation', () => {
      it('keeps punc', () =>
        expect(titleWithPunc(`crap bEER's #1 baby some-dash #2hi`)).toEqual(
          `Crap Beer's #1 Baby Some-dash #2Hi`
        ));

      it('keeps punc', () =>
        expect(
          titleWithPunc(`crap bEER's #1 baby some-dash #2hi`, { doLowerRest: false })
        ).toEqual(`Crap BEER's #1 Baby Some-dash #2Hi`));
    });
  });
});

```

**Comment by blakeembrey** [comment]
It does sound like a good idea, yes!

**Comment by demedos** [comment]
+1 for optional `noCase`. When I used `titleCase` I didn't expect punctuation to be removed

**Comment by blakeembrey** [comment]
A `title-case` that's unrelated to `change-case` has been released and should solve this for you.
