### ISSUE TITLE
Module '"node_modules/change-case/change-case"' has no default export

### ISSUE THREAD

**Issue by Nikhil-Daffodil** [blakeembrey/change-case#57]
In ionic 4 while importing changeCase from change-case it is throwing this error **Module '"/node_modules/change-case/change-case"' has no default export** It working fine in ionic 3

**Comment by blakeembrey** [comment]
@Nikhil-Daffodil What exactly do you expect to be done here? There is not default export from this module.

**Comment by Nikhil-Daffodil** [comment]
@blakeembrey why I'm getting this error when I'm importing the change-case module in ionic 4, it is working fine in ionic 3 

**import changeCase from "change-case"**

**Comment by blakeembrey** [comment]
Nothing in this module changed. You should read the Ionic documentation. You should probably be using the module like `import * as changeCase` instead of how you currently are though.
