### ISSUE TITLE
Support tree-shaking with `import { camelCase } from 'change-case'`

### ISSUE THREAD

**Issue by mesqueeb** [blakeembrey/change-case#59]
Hello.
I never write `require('  ')` in my apps, so I'm not sure their support for tree-shaking.
But with the official ES import method:
```js
import { camelCase } from 'change-case'
```
this would allow webpack and rollup to tree-shake the 'change-case' package to only include `camelCase` for example.

Is this possible with your package as well?

**Comment by yfrommelt** [comment]
It's actually works just like that right now.
I use it in my project with 
`import {camelCase, titleCase} from 'change-case'`

**Comment by blakeembrey** [comment]
The ES imports would always work due to how to treat CommonJS packages, but the latest major version exports native ES modules which will also tree-shake.
