### ISSUE TITLE
ucFirst removed ?

### ISSUE THREAD

**Issue by ph55** [blakeembrey/change-case#64]
```
 import { ucFirst } from 'change-case';
```

Updated from `3.1.0` to `4.0.0`.
Why removing function instead of deprecation?

Also it's not clear how to import `upperCaseFirst`.

**Comment by blakeembrey** [comment]
@ph55 It's a major version change. That's how semver works. What's unclear about the import?

**Comment by blakeembrey** [comment]
@ph55 To be clear, `upperCaseFirst` isn't part of `change-case` anymore. It _could_ be added easily, but since it didn't follow the rest of the "change case" conventions I removed it in this major version. You can read the docs under https://github.com/blakeembrey/change-case#other-case-utilities.

**Comment by ph55** [comment]
@blakeembrey Ok, got it.

Regarding imports, neither
```
import * as changeCase from 'change-case';
changeCase.upperCaseFirst('text');

// method not found
```

nor

```
import { upperCaseFirst } from 'change-case';

// has no exported member 'upperCaseFirst'
```

Works

**Comment by ph55** [comment]
@blakeembrey 

I see that I could add it via

```
import { upperCaseFirst } from 'upper-case-first';
```

Worth to mention in docs IMO.
Thanks.

**Comment by blakeembrey** [comment]
I clarified the README a little bit (first time dealing with a mono-repo), let me know if it helps. `upperCaseFirst` is a separate library.

**Comment by blakeembrey** [comment]
> Worth to mention in docs IMO.

How would you document this? Can you submit a PR? It's documented on the library page.

**Comment by ph55** [comment]
Oh I see, it's mono–repo. It was my confusion then :)
All clear now, thanks.

When `change-case` installed I see that `upper-case-first` installed automatically though.

**Comment by blakeembrey** [comment]
It is a dependency of some of the case changing libraries (e.g. camel case), but you shouldn’t rely on it without depending on it yourself.

**Comment by ceefour** [comment]
May I know what was the rationale for splitting the original project into many tiny projects?

Many projects are now essentially one liners, e.g.

```
export function upperCaseFirst(input: string) {
  return input.charAt(0).toUpperCase() + input.substr(1);
}
```

It takes longer (to download, build, etc.) for a project to depend on many small npm packages instead of one-two reasonably sized libraries with multiple functions. I'm really curious why the refactor was made, and what the benefits are, since there are disadvantages as well (see: [Monorepo anti-pattern](https://medium.com/@PepsRyuu/monorepos-in-javascript-anti-pattern-917603da59c8)).

**Comment by blakeembrey** [comment]
FWIW, this was not a change. This was originally many different packages, the only change is a monorepo.
