### ISSUE TITLE
Add default export to packages

### ISSUE THREAD

**Issue by vweevers** [blakeembrey/change-case#65]
Since v3, `require('snake-case')` and others no longer return a function:

```
$ node
> require('snake-case')
{ snakeCase: [Function: snakeCase] }
```

Is that by design?

**Comment by blakeembrey** [comment]
Yes, the document is up to date.

**Comment by blakeembrey** [comment]
Let me know if there’s any concerns with using it this way though!

**Comment by vweevers** [comment]
I have a CLI that takes a `--case` option, which is the name of one of the change-case packages (or any other npm package that exports a single function) e.g. `--case snake-case`. This worked because they all had the same interface. It's not important, I can work around it.
