### ISSUE TITLE
Changelog for major release

### ISSUE THREAD

**Issue by gr2m** [blakeembrey/change-case#66]
Hi Blake,

thank you for maintaining all these small, focused packages.

I wonder if you keep track of changes between releases somewhere? I've looked around but couldn't find them. I'm in particular interested in the breaking changes of `pascal-case@v3'

**Comment by blakeembrey** [comment]
Thanks, I didn’t get around to it last night but will today. The main changes are:

1. Removed Unicode support in favor of ASCII alphanumeric (this support added over 5KB for browsers and I couldn’t see any usage)
2. Changed export from `module.exports` to named export per package (this was part of refactoring for ES2015 module which supports tree shaking for browsers)

If 1 is of interest to you, thanks to the design of the refactor it is possible to support, via configuration, the old RegExps which would make the package functionally backward compatible.

**Comment by gr2m** [comment]
Thanks Blake. I don't think I'm affected by 1. myself

**Comment by niftylettuce** [comment]
See #67, there is a core breaking bug in v3.0.0

**Comment by blakeembrey** [comment]
Release notes added to GitHub Releases: https://github.com/blakeembrey/change-case/releases.

To @niftylettuce's point, there's actually a third breaking change:

If you previously used any of the additional arguments to customize behavior, they are contained within an `Options` object now.
