### ISSUE TITLE
Core bug with latest release

### ISSUE THREAD

**Issue by niftylettuce** [blakeembrey/change-case#67]
```sh
  Error thrown in test:

  TypeError {
    message: 'Cannot destructure property `splitRegexp` of \'undefined\' or \'null\'.',
  }

  noCase (node_modules/no-case/src/index.ts:20:9)
  maskString (src/index.js:199:25)
  maskProps (src/index.js:253:18)
  parseRequest (src/index.js:400:12)
  test/basic.js:518:15
```

**Comment by blakeembrey** [comment]
@niftylettuce What's the reproduction? Are you passing `null` as the second argument somewhere?

**Comment by niftylettuce** [comment]
@blakeembrey yeah <https://github.com/cabinjs/parse-request/blob/master/src/index.js#L199

**Comment by niftylettuce** [comment]
I supposed I could switch from `noCase` to `snakeCase`, but just wanted to point it out that as soon as I version bumped and changed `const noCase` to `const { noCase }` it caused that exception.

**Comment by blakeembrey** [comment]
@niftylettuce Thanks for the flag, I'm documenting it now - the second argument should be an `object` or `undefined`.

**Comment by blakeembrey** [comment]
FWIW, all functions have an `object` as the second argument now. Documentation in `no-case` is here: https://github.com/blakeembrey/change-case/tree/master/packages/no-case#options. I might pull it up to the top-level README where it's more visible instead.

**Comment by blakeembrey** [comment]
Added document to main README on options: https://github.com/blakeembrey/change-case#core.

**Comment by niftylettuce** [comment]
You rock, thanks @blakeembrey 🎉 	Have an awesome rest of your weekend
