### ISSUE TITLE
Not documented breaking change - `lowerCase` and `titleCase` are no longer exported.

### ISSUE THREAD

**Issue by ardatan** [blakeembrey/change-case#68]
After v4, `lowerCase` and `titleCase` are no longer exported but it used to be exported in older versions.

**Comment by blakeembrey** [comment]
That is correct, it's documented here: https://github.com/blakeembrey/change-case/releases/tag/change-case%404.0.0 and here: https://github.com/blakeembrey/change-case#core. If either of those were unclear please let me know how to improve it.

**Comment by blakeembrey** [comment]
Title case is changes are also documented here: https://github.com/blakeembrey/change-case/releases/tag/title-case%403.0.0 (it's not the same package, I altered behavior because I received numerous issues and complaints over the years due to unexpected `title-case` behavior).
