### ISSUE TITLE
Regression: change-case v4 no longer accepts `undefined`

### ISSUE THREAD

**Issue by bajtos** [blakeembrey/change-case#69]
Consider the following code:

```
require('change-case').camelCase()
```

Using `change-case` version 3.x (`3.1.0`), this code works and returns and empty string `''`.

Using `change-case` version 4.x (`4.0.0`), this code throws the following error:

```
TypeError: Cannot read property 'replace' of undefined
    at Object.noCase (node_modules/no-case/dist/index.js:14:10)
    at Object.pascalCase (node_modules/pascal-case/dist/index.js:15:22)
    at Object.camelCase (node_modules/camel-case/dist/index.js:11:26)
```

Assuming this new behavior is intended: can we document the change in release notes please?

**Comment by blakeembrey** [comment]
I’ll get to this later tonight, but yes - you are correct. The input is expected to be a string.

**Comment by blakeembrey** [comment]
Actually, how is https://github.com/blakeembrey/change-case/releases/tag/no-case%403.0.0?

**Comment by bajtos** [comment]
> Actually, how is https://github.com/blakeembrey/change-case/releases/tag/no-case%403.0.0?

Perfect 👍 Thank you! ❤️
