### ISSUE TITLE
.titleCase() shouldn't lower user's input capital case

### ISSUE THREAD

**Issue by chongwang87** [blakeembrey/change-case#7]
as per title, for example user key in "CCTV distributor", it should convert to "CCTV Distributor" instead of "Cctv Distributor"

**Comment by danielbayley** [comment]
Why not just something like `\b([a-z])(?!=[A-Z])` to avoid abbreviations?

**Comment by blakeembrey** [comment]
Change case is only involved with converting cases between various forms, not supporting proper title case. It's unfortunate that this has created confusion and I would love to repair that, but for now it'll remain the same.

**Comment by danielbayley** [comment]
Fair enough, but I think the confusion arises from the fact that what this actually does is ‘Capitalise’ as opposed to actual title case.

**Comment by blakeembrey** [comment]
Absolutely. And I'm definitely going to change it if the need for a 3.x arrises. Sorry for the confusion!
