### ISSUE TITLE
3 -> 4 migration guide

### ISSUE THREAD

**Issue by oprogramador** [blakeembrey/change-case#70]
Could you publish a migration guide explaining how to upgrade `change-case` from v3 to v4?
My tests passed after upgrading but I'd like to ensure.

In https://github.com/blakeembrey/change-case/releases I see tags for partial packages like `title-case` or `swap-case` but I see no tags for `change-case`.

**Comment by blakeembrey** [comment]
Check the second page, but there’s also an existing closed issue where we went over the changes.

**Comment by oprogramador** [comment]
Thanks, I found release notes for `change-case@4` but I see no breaking changes listed.

**Comment by blakeembrey** [comment]
Everything in https://github.com/blakeembrey/change-case/releases/tag/change-case%404.0.0 is a breaking change. If you'd like to update the documentation, feel free to leave a comment here and I'll update it accordingly. You probably want to check each package for their individual breaking changes (which is the same breaking change 10 times).

**Comment by blakeembrey** [comment]
Feel free to contribute a migration guide if you think it'd be useful too. I believe everything was covered in release notes already, but there's also https://github.com/blakeembrey/change-case/issues/66.

**Comment by oprogramador** [comment]
@blakeembrey 

I checked I use only `snake-case`, having the entire `change-case` installed.
So is there anything I should update?

**Comment by blakeembrey** [comment]
@oprogramador Is the documentation currently unclear? Feel free to submit a PR with a migration guide. Documentation on the change: https://github.com/blakeembrey/change-case/releases/tag/title-case%403.0.0, new package https://github.com/blakeembrey/change-case/releases/tag/capital-case%401.0.0, core change (linked from every `change-case` bump): https://github.com/blakeembrey/change-case/releases/tag/no-case%403.0.0.

**Comment by oprogramador** [comment]
So I `titleCase` is renamed into `capitalCase`.

`Accepts a string and automatically capitalizes words based on English "Title Case" logic` - could you give an example of changing this behavior?

**Comment by blakeembrey** [comment]
https://github.com/blakeembrey/change-case/tree/master/packages/title-case

**Comment by blakeembrey** [comment]
Also https://en.wikipedia.org/wiki/Letter_case#Title_case (which I'll link in that README now).

**Comment by oprogramador** [comment]
I know what title case is but has anything changed in the behavior of this function (any edge cases)?

**Comment by blakeembrey** [comment]
@oprogramador It's an entirely different package now, as noted in the releases.

**Comment by blakeembrey** [comment]
I linked to all the possible release notes above, but again, these are your main changes: https://github.com/blakeembrey/change-case/releases/tag/no-case%403.0.0 - if it's not documented, what edge case are you asking about? Unicode capitalization no longer works, that's the largest breaking change. Everything else is the same minus renames, changes to args, etc - the core behavior (how `capitalCase` works) is the same.

**Comment by oprogramador** [comment]
For `change-case@3` I see this:
```
> c=require('change-case')
{ noCase: [Function],
  no: [Function],
  dotCase: [Function],
  dot: [Function],
  swapCase: [Function],
  swap: [Function],
  pathCase: [Function],
  path: [Function],
  upperCase: [Function],
  upper: [Function],
  lowerCase: [Function],
  lower: [Function],
  camelCase: [Function],
  camel: [Function],
  snakeCase: [Function],
  snake: [Function],
  titleCase: [Function],
  title: [Function],
  paramCase: [Function],
  param: [Function],
  kebabCase: [Function],
  kebab: [Function],
  hyphenCase: [Function],
  hyphen: [Function],
  headerCase: [Function],
  header: [Function],
  pascalCase: [Function],
  pascal: [Function],
  constantCase: [Function],
  constant: [Function],
  sentenceCase: [Function],
  sentence: [Function],
  isUpperCase: [Function],
  isUpper: [Function],
  isLowerCase: [Function],
  isLower: [Function],
  upperCaseFirst: [Function],
  ucFirst: [Function],
  lowerCaseFirst: [Function],
  lcFirst: [Function] }
> c.capitalCase('aa ddd')
Thrown:
TypeError: c.capitalCase is not a function
> c.titleCase('aa ddd')
'Aa Ddd'
>
```

and for `change-case@4`:
```
> c=require('change-case')
{ camelCaseTransform: [Function: camelCaseTransform],
  camelCase: [Function: camelCase],
  capitalCaseTransform: [Function: capitalCaseTransform],
  capitalCase: [Function: capitalCase],
  constantCase: [Function: constantCase],
  dotCase: [Function: dotCase],
  headerCase: [Function: headerCase],
  noCase: [Function: noCase],
  paramCase: [Function: paramCase],
  pascalCaseTransform: [Function: pascalCaseTransform],
  pascalCase: [Function: pascalCase],
  pathCase: [Function: pathCase],
  sentenceCaseTransform: [Function: sentenceCaseTransform],
  sentenceCase: [Function: sentenceCase],
  snakeCase: [Function: snakeCase] }
> c.titleCase('aa ddd')
Thrown:
TypeError: c.titleCase is not a function
> c.capitalCase('aa ddd')
'Aa Ddd'
>
```

So I have 2 questions:
1) Does the new `capitalCase` works exactly the same as the old `snakeCase`?
2) Why did you remove so many methods?

**Comment by blakeembrey** [comment]
1. No, it's documented in the release notes I've already linked you. Capital case and snake case are entirely different functions.
2. Because I maintain this for free and want to reduce the amount of labor I need to put into all packages I maintain. Some of those functions were not like the others and created needless documentation and confusion. If you want those functions that do something entirely different to the rest, you can install them separately. Most people don't use them, so why install them?

**Comment by oprogramador** [comment]
Sorry. I meant is the new `capitalCase` the same as the old `titleCase`

**Comment by blakeembrey** [comment]
No, it has the same changes I linked above. I'll copy the important points inline for you: 

* Function accepts two arguments: `string` (required) and `Options` (optional)
* Default behavior of `RegExp` is to split on ASCII chacters only (previously it used a Unicode RegExp, but this added 5 KB)

**Comment by oprogramador** [comment]
I see previously the second param was locale.
Anyway I pass only one param so I guess it should work in the same way.

**Comment by blakeembrey** [comment]
> Anyway I pass only one param so I guess it should work in the same way.

Unless you previously relied on unicode characters being detected when converting `camelÇase`, yes. It would largely would the same. The 5 KB overhead to support that case wasn't worth maintaining, considering people would like to use this library in browsers. When unicode regexes get standardized (e.g. IE is dead), we can support unicode again.

**Comment by oprogramador** [comment]
thanks
