### ISSUE TITLE
Version 4: camelcase merge numbers option removed?

### ISSUE THREAD

**Issue by stevethatcodes** [blakeembrey/change-case#72]
This is more of a question rather than an issue. In version 3.x, we used the `mergeNumbers` option when invoking `camelCase`, example:

```
const camelCase('some_field_1', '', true); // -> someField1
```

Since upgrading to version 4, it looks like the options accepted by `camelCase` have been centralised, and this feature has been lost, is this correct?

Is there a recommended way to achieve the above with version 4?

**Comment by blakeembrey** [comment]
Change the “transform” function.

**Comment by blakeembrey** [comment]
It’s possible the camel case function could expose alternative transforms as code too, then you’d need to import and use the alternative config.

**Comment by stevethatcodes** [comment]
> Change the “transform” function.

Thanks for the heads up, I can do something like this and get the existing behaviour restored:

```
camelCase('some_field_1', {
        transform: (segment: string, index: number) => {
            return index === 0
                ? segment
                : `${segment.charAt(0).toUpperCase()}${segment.substr(1)}`;
        }
}) // -> someField1
```

It would be great if camelCase exposed a transform to achieve this though, I can see this being quite a common use case for the library to handle.

I noticed that the transform option isn't really documented, would you be open to a PR to add some docs?

**Comment by blakeembrey** [comment]
Sure, there’s existing documentation in the README that can be expanded on.

**Comment by blakeembrey** [comment]
Added the functionality back natively to `camelCase` and `pascalCase`: https://github.com/blakeembrey/change-case/blob/master/packages/camel-case/README.md#merge-numbers.

**Comment by stevethatcodes** [comment]
> Added the functionality back natively to `camelCase` and `pascalCase`: https://github.com/blakeembrey/change-case/blob/master/packages/camel-case/README.md#merge-numbers.

Amazing, thanks so much for the quick turnaround on this.
