### ISSUE TITLE
Preserve non alphanumerical characters

### ISSUE THREAD

**Issue by jagaapple** [blakeembrey/change-case#74]
I love this package, but when I updated from 3.1.0 to 4.1.0, I realized the behavior. It's to remove non alphanumerical characters like the following.

```js
changeCase.camelCase("hello hello"); // "helloHello"
changeCase.camelCase("hello hello!"); // "helloHello"
changeCase.camelCase("!!!"); // ""
```

[As release notes said](https://github.com/blakeembrey/change-case/releases/tag/no-case%403.0.0), the latest version does not support unicode conversion so I think it's expected, but if our users use English in our projects which handle i18n, it should be converted any cases such as title case. Do you have a plan to re-implement to preserve them such as using option?

**Comment by blakeembrey** [comment]
@jagaapple This hasn't changed since 3.1.0 and all your examples work the same on 3.1.0, I can't replicate any difference.

**Comment by jagaapple** [comment]
@blakeembrey Ahh, I just realized it's multibyte characters correctly like the following.

```js
// 3.1.0
changeCase.camelCase("あああ"); // "あああ"

// 4.1.0
changeCase.camelCase("あああ"); // ""
```

And do you have a plan to implement to preserve non-alphanumerical and multibyte characters when changing?

**Comment by blakeembrey** [comment]
@jagaapple Would adding it as a configuration option work for you? The reason it isn't supported by default anymore is because it added something like 26KB to browsers. See https://bundlephobia.com/result?p=change-case@4.1.0 for the changes.

**Comment by jagaapple** [comment]
@blakeembrey hmm... if I can get solutions, I'll create pull request! Thank you😃

**Comment by blakeembrey** [comment]
@jagaapple Probably re-exposing a `RegExp` built from `XRegExp` - that's what the previous versions did. We could put it in a separate package by default and you'd just need to import and add to the `options`.
