### ISSUE TITLE
Breaking change in `pascal-case` in 3.x.x

### ISSUE THREAD

**Issue by ardatan** [blakeembrey/change-case#76]
```js
const { pascalCase } = require("pascal-case");
pascalCase("IQueryAArgs") 
```
This code used to give `IQueryAArgs` before 3.x.x, but now it gives `IQueryAargs`.

**Comment by blakeembrey** [comment]
Thanks for the flag. This looks related to merging the regexes in `no-case` together into a single regex, so the first would split it apart but the same fails to also split `AA`. Looking at a fix today.

**Comment by blakeembrey** [comment]
Fixed with https://github.com/blakeembrey/change-case/commit/d945e02b515cb8f7797328bcc5d6a29eb6c5832d.
