### ISSUE TITLE
Undefined not accepted

### ISSUE THREAD

**Issue by cloverb** [blakeembrey/change-case#80]
Hello, I am still seeing this regression with the current version of change-case: https://github.com/blakeembrey/change-case/issues/69.

Repro: https://repl.it/@cloverb/PlaintiveVacantCryptocurrency.

Is this going to be fixed or do you intend it to be a breaking change?

**Comment by blakeembrey** [comment]
It was a breaking change, hence the major version bump.

**Comment by blakeembrey** [comment]
The issue you linked to also said it was intentional, that was just about it missing from release notes.
