### ISSUE TITLE
Is it working with objects?

### ISSUE THREAD

**Issue by macabeus** [blakeembrey/change-case#81]
Currently, some functions such as `camelCase` works well with objects:

![image](https://user-images.githubusercontent.com/9501115/75968272-04c7e980-5ec5-11ea-9104-808d68c6c35d.png)

But I don't know if it's an expected behaviour, because there is no documentation saying that it works with objects [and the type expectes only strings](https://github.com/blakeembrey/change-case/blob/1c1377a692d328ae01221b2a1532bade38e1eaa3/packages/camel-case/src/index.ts#L20).

I think that would be very useful this package works with objects.

**Comment by blakeembrey** [comment]
That’s a different package altogether, not something I maintain.

**Comment by blakeembrey** [comment]
It looks like your using https://www.npmjs.com/package/change-case-object.

**Comment by macabeus** [comment]
@blakeembrey Oh, sorry! I misclicked on very some crazy way.
