### ISSUE TITLE
snake case of "ImageURLs" returns "image_ur_ls"

### ISSUE THREAD

**Issue by arafathusayn** [blakeembrey/change-case#85]
Is it intended to separate an uppercase letter followed by a lower case letter with an underscore? 
For example, `snakeCase("ImageURLs") `returns `"image_ur_ls"`. Shouldn't it return `"image_urls"`?

Link to try: https://runkit.com/embed/7g2z45mdxmoc

**Comment by blakeembrey** [comment]
This is currently the intended behavior. You can customize it like mentioned in the README. Imagine the browser APIs such as `XMLHttpRequest`. It’s unfortunate but impossible to handle every case without a dictionary.
