### ISSUE TITLE
Consider extending functionality to allow changing case of object keys

### ISSUE THREAD

**Issue by uladkasach** [blakeembrey/change-case#86]
Hey there! Great package and i love the api you've exposed. 

Have you considered expanding the scope of this project to expose a utility to recursively change the case of keys of an object?

For example:
```ts
const user = {
  firstName: 'foo',
  lastName: 'bar',
};
const snakeCaseUser = snakeCaseKeys(user); 
/*
{
  first_name: 'foo',
  last_name: 'bar',
}
*/
```

**Comment by blakeembrey** [comment]
@uladkasach It's not something I've wanted to maintain before, but I could see it being useful as a package that takes `changeKeys(obj, renameFn)` instead of wrapping each module independently.

**Comment by uladkasach** [comment]
Would you be comfortable with me adding that function to this package? 

e.g.:

```
import { snakeCase, changeKeys } from 'change-case';
const user = {
  firstName: 'foo',
  lastName: 'bar',
};
const snakeCaseUser = changeKeys(user, snakeCase); 
/*
{
  first_name: 'foo',
  last_name: 'bar',
}
*/
```

**Comment by dmytro-shchurov** [comment]
> @uladkasach It's not something I've wanted to maintain before, but I could see it being useful as a package that takes `changeKeys(obj, renameFn)` instead of wrapping each module independently.

This could be highly appreciated by all developers who need to work with API in Python. It's simpler to make the conversion on a client side than to explain them why do we need this.

**Comment by AckerApple** [comment]
We at [BStock.com](https://bstock.com) needed and wanted this code described in this issue.

We have done the work with testing and would like to request @uladkasach to review and implement as a pull request. If weeks go by and no movement then we will make the official pull request.

The code needed:
```ts
export function changeKeys(
  obj: any,
  casing: (v: string, ops?: any) => string
): any {
  if (!obj || obj.constructor !== Object) {
    return obj
  }

  return Object.keys(obj).reduce((all: any, key) => {
    const newKey = casing(key)
    all[newKey] = obj[key] && obj[key].constructor === Object ?
      changeKeys(obj[key], casing) : obj[key]
    return all
  }, {})
}
```

The unit test like code we used to verify our functionality:
```ts
import { camelCase } from 'change-case'

describe('toCamelCase', () => {
  it('should convert 1 level object', () => {
    const obj = {site_abb: 'test-site', entity_id: 'test-entity-id'}
    const res = changeKeys(obj, camelCase)

    expect(res).toStrictEqual({siteAbb: 'test-site', entityId: 'test-entity-id'})
  })

  it('should convert multi level object', () => {
    const obj = {
      card: {
        exp_month: 11,
        exp_year: 2023,
        brand: 'Visa',
        address_line1_check: 'unchecked',
        address_zip_check: 'unchecked',
        field1: null,
        test_field2: null,
      },
      owner: {
        address: {
          postal_code: '33066',
          state: 'FL',
        },
      },
    }

    const expected = {
      card: {
        expMonth: 11,
        expYear: 2023,
        brand: 'Visa',
        addressLine1Check: 'unchecked',
        addressZipCheck: 'unchecked',
        field1: null,
        testField2: null,
      },
      owner: {
        address: {
          postalCode: '33066',
          state: 'FL',
        },
      },
    }

    const res = changeKeys(obj, camelCase)
    expect(res).toStrictEqual(expected)
  })

  it('should not fail if it got not an object', () => {
    expect(changeKeys(null, camelCase)).toBe(null)
    expect(changeKeys(undefined, camelCase)).toBe(undefined)
    expect(changeKeys(1, camelCase)).toBe(1)
    expect(changeKeys('abc', camelCase)).toBe('abc')
    expect(changeKeys(['a', 'b', 'c'], camelCase)).toStrictEqual(['a', 'b', 'c'])
  })
})
```

**Comment by uladkasach** [comment]
Finally got around to contributing this :sweat_smile:

**Comment by uladkasach** [comment]
bumping this up again, i think its ready to merge: https://github.com/blakeembrey/change-case/pull/240

**Comment by austinbiggs** [comment]
Bump 😸

**Comment by blakeembrey** [comment]
This has been added to `change-case@5` as an ESM import of `change-case/keys`, based on the work in https://github.com/blakeembrey/change-case/pull/240.
