### ISSUE TITLE
Add "smash" case or similar

### ISSUE THREAD

**Issue by cvburgess** [blakeembrey/change-case#93]
In some scenarios it is useful to strip out all the word seperators and create a "smashed" output like so:

```js
smashCase("test string");
//=> "teststring"
```

**Comment by blakeembrey** [comment]
Not sure this will be included by default, but it should be easy to do by taking `no-case` and replacing the options: https://github.com/blakeembrey/change-case#options.

**Comment by cvburgess** [comment]
Very true! I obviously have uses for this as there are many places where our apps need to remove all seperators. setting `delimiter: ""` works but i still would love to see some first-class support if I am not alone ( i very well may be ).
