### ISSUE TITLE
Underscores to CamelCase doesnt do numbers!

### ISSUE THREAD

**Issue by mpaccione** [blakeembrey/change-case#94]
Hi when I try to convert "address_country_2" to "addressCountry2" I get "addressCountry_2"

Naturally this defeats the use case of the library for me.

Is there any chance of getting this fixed?

**Comment by jamesncampbell** [comment]
@mpaccione Did you find any workaround for this? Experiencing the same thing

**Comment by mpaccione** [comment]
I just put in some if else statements because it was a small implementation...

I could just write my own implementation not too hard really. Although maybe best to do a pull request on this issue and just fix it. 

I'm too busy right now for anything but making the initial issue.

Cheers and good luck!

**Comment by OscarBarrett** [comment]
https://github.com/blakeembrey/change-case/blob/cd631f5bdc537fea5a4415c193ec0074fded0aaf/packages/pascal-case/README.md#merge-numbers

**Comment by mpaccione** [comment]
Is that only for PascalCase or does the same functionality work for camelCase?

**Comment by OscarBarrett** [comment]
Yeah seems it was added back in a few months ago. https://github.com/blakeembrey/change-case/blob/master/packages/camel-case/README.md#merge-numbers

#72

**Comment by mpaccione** [comment]
Ha! Well that great to know. What got me was that it appeared that the docs were on the main readme page but there are more specific docs upon clicking through.
