### ISSUE TITLE
lower-case cannot be compiled with google-closure-compiler

### ISSUE THREAD

**Issue by jscheid** [blakeembrey/change-case#96]
```
$ yarn init
$ yarn add lower-case google-closure-compiler-java
$ java -jar node_modules/google-closure-compiler-java/compiler.jar node_modules/lower-case/dist.es2015/index.js
node_modules/lower-case/dist.es2015/index.js:10: 
Originally at:
node_modules/lower-case/src/index.ts:18: ERROR - [JSC_PARSE_ERROR] Parse error. Character '̇' (U+0307) is not a valid identifier start char

1 error(s), 0 warning(s)
$ java -jar node_modules/google-closure-compiler-java/compiler.jar node_modules/lower-case/dist/index.js
node_modules/lower-case/dist/index.js:12: 
Originally at:
node_modules/lower-case/src/index.ts:18: ERROR - [JSC_PARSE_ERROR] Parse error. Character '̇' (U+0307) is not a valid identifier start char

1 error(s), 0 warning(s)
```

I've tried normalizing the file using uconv with any-nfc or any-nfd, but same result.

I don't currently have more time to deep-dive into it and figure out whether g-c-c is right to complain here, but they [seem to know their Unicode](https://github.com/google/closure-compiler/issues/2544).

If it really is an invalid start character then this is possibly a bug in tsc, which you'd expect to either raise an error or add quotes. There also seems to be a related bug in prettier, which strips quotes if I add them.

Either way, a pragmatic solution might be to quote the offending identifiers in this package?

**Comment by blakeembrey** [comment]
There's not a single non-ASCII character in that file from what I can tell.

**Comment by blakeembrey** [comment]
Actually, I missed it - was looking at the regexp - it's the keys 🤕 It seems like a bug in `google-closure-compiler` if node.js and prettier both handle it correctly.

**Comment by blakeembrey** [comment]
As far as I can tell, the comment in that thread is incorrect too. It links to an article that actually says it's a valid identifier and there's a tool to test here: https://mothereff.in/js-variables#ಠ.

**Comment by jscheid** [comment]
Sure, you're probably right, it's a bit hard to tell with different ES versions, different Unicode normalizations etc.

I guess I was proposing that you might change it anyway, in the spirit of (a variant of) Postel's Law. After all, even if they fix it in g-c-c there are still going to be people using older versions for a while.

That being said, I've removed your lib from our package for now and replaced it with some hand written code, so I no longer have a horse in the race. Feel free to close this.

**Comment by blakeembrey** [comment]
No problem. It's definitely unfortunate. I'd prefer to stick with using standardized forms everywhere because it's a lot of work to maintain many different packages in different formats. Prettier is unfortunately another version of that, I'm sorry it caused you issues in this case.
