### ISSUE TITLE
Empty result when trying to change case to japanese string

### ISSUE THREAD

**Issue by spinlud** [blakeembrey/change-case#97]
```js
const s = '機種';

console.log(constantCase(s)); // gives empty result
```

Is this the supposed behaviour?

**Comment by blakeembrey** [comment]
Yes, it doesn’t support non-ASCII strings. At least not until Unicode regexp matches are stable in browsers.

**Comment by blakeembrey** [comment]
You can change the regexp to support this, I can provide an example regexp with complete unicode support - maybe even put it in a separate package if it helps you.

**Comment by spinlud** [comment]
I will live with that for the moment, disabling transformations for non ASCII strings and waiting for a more general support.
Thanks for the support!
