### ISSUE TITLE
titleCase function in title-case isn't returning correct title case format for all strings.

### ISSUE THREAD

**Issue by tazzzzzzz** [blakeembrey/change-case#99]
![image](https://user-images.githubusercontent.com/47104651/80854761-7c618d00-8c58-11ea-8672-9ed993595ef4.png)

**Comment by blakeembrey** [comment]
It's impossible to do everything you want, e.g. it would need to know every possible word in the world to correctly handle your first suggestion with things like iPad, iPhone, iPod, NASA, etc.

**Comment by blakeembrey** [comment]
If you didn't care about the original casing at all, you could use the capital case package: https://github.com/blakeembrey/change-case#capitalcase.

Alternatively, you can just do `titleCase(sentence.toLowerCase())`.
